version: '3.8'

services:
  # FTP Server
  ftp-server:
    image: stilliard/pure-ftpd
    container_name: test-ftp-server
    ports:
      - "21:21"
      - "30000-30009:30000-30009"
    environment:
      PUBLICHOST: localhost
      FTP_USER_NAME: testuser
      FTP_USER_PASS: testpass
      FTP_USER_HOME: /home/ftpuser
    volumes:
      - ftp-data:/home/ftpuser
      - ./test/ftp-config:/etc/pure-ftpd/conf
    restart: unless-stopped

  # SFTP Server  
  sftp-server:
    image: atmoz/sftp
    container_name: test-sftp-server
    ports:
      - "2222:22"
    environment:
      SFTP_USERS: testuser:testpass:1001:1001:upload
    volumes:
      - sftp-data:/home/testuser/upload
    restart: unless-stopped

volumes:
  ftp-data:
  sftp-data:
