name: Integration Tests

on:
  workflow_call:

jobs:
  integration-test:
    runs-on: ubuntu-latest
    
    services:
      # FTP Server
      ftp-server:
        image: stilliard/pure-ftpd
        ports:
          - 21:21
          - 30000-30009:30000-30009
        env:
          PUBLICHOST: localhost
          FTP_USER_NAME: testuser
          FTP_USER_PASS: testpass
          FTP_USER_HOME: /home/ftpuser
        volumes:
          - ${{ github.workspace }}/test-ftp-data:/home/ftpuser

      # SFTP Server
      sftp-server:
        image: atmoz/sftp
        ports:
          - 2222:22
        env:
          SFTP_USERS: testuser:testpass:1001:1001:upload
        volumes:
          - ${{ github.workspace }}/test-sftp-data:/home/testuser/upload

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Wait for servers to be ready
      run: |
        echo "Waiting for FTP server..."
        timeout 120 bash -c 'until nc -z localhost 21; do echo "FTP not ready, waiting..."; sleep 2; done'
        echo "FTP server is ready!"
        
        echo "Waiting for SFTP server..."
        timeout 120 bash -c 'until nc -z localhost 2222; do echo "SFTP not ready, waiting..."; sleep 2; done'
        echo "SFTP server is ready!"
        
        echo "Giving services additional time to fully initialize..."
        sleep 5

    - name: Run Integration Tests
      run: ./test/integration-test.sh ci

    - name: Verify files in mounted volumes
      run: |
        echo "=== Mounted Volume Verification ==="
        echo "FTP Server Files:"
        find ${{ github.workspace }}/test-ftp-data -type f 2>/dev/null | head -20 || echo "No FTP files found"
        
        echo ""
        echo "SFTP Server Files:"
        find ${{ github.workspace }}/test-sftp-data -type f 2>/dev/null | head -20 || echo "No SFTP files found"
        
        # Verify key test files exist in both servers
        echo ""
        echo "=== Critical File Verification ==="
        
        # Check FTP files
        FTP_FILES=("${{ github.workspace }}/test-ftp-data/initial/index.html"
                   "${{ github.workspace }}/test-ftp-data/initial/assets/logo.txt"
                   "${{ github.workspace }}/test-ftp-data/nochange/index.html")
        
        echo "Checking FTP files..."
        for file in "${FTP_FILES[@]}"; do
          if [ -f "$file" ]; then
            echo "✅ FTP: $(basename "$file")"
          else
            echo "❌ FTP: $(basename "$file") - MISSING"
            exit 1
          fi
        done
        
        # Check SFTP files  
        SFTP_FILES=("${{ github.workspace }}/test-sftp-data/initial/index.html"
                    "${{ github.workspace }}/test-sftp-data/initial/assets/logo.txt"
                    "${{ github.workspace }}/test-sftp-data/changes/index.html")
        
        echo "Checking SFTP files..."
        for file in "${SFTP_FILES[@]}"; do
          if [ -f "$file" ]; then
            echo "✅ SFTP: $(basename "$file")"
          else
            echo "❌ SFTP: $(basename "$file") - MISSING"
            exit 1
          fi
        done
        
        echo ""
        echo "🎉 All critical files verified in mounted volumes!"

    # Cleanup
    - name: Cleanup test files
      if: always()
      run: |
        rm -f ./.ftp-*.json
        rm -f ./.sftp-*.json
        rm -rf ${{ github.workspace }}/test-ftp-data
        rm -rf ${{ github.workspace }}/test-sftp-data